### ISSUE TITLE
Complete CloudApiClient

### ISSUE THREAD

**Issue by webbj74** [acquia/acquia-sdk-php#12]
The CloudApiClient class is missing methods for the following API functions
- [x] List a site’s tasks. [See #11]
  - GET /sites/:site/tasks
- [x] Copy files from one site environment to another.
  - POST /sites/:site/files-copy/:source/:target
- [x] Deploy code from one site environment to another.
  - POST /sites/:site/code-deploy/:source/:target
- [x] Add a database.
  - POST /sites/:site/dbs
- [x] Copy a database from one site environment to another.
  - POST /sites/:site/dbs/:db/db-copy/:source/:target
- [x] Delete a database.
  - DELETE /sites/:site/dbs/:db
- [x] Move domain(s) from one site environment to another.
  - POST /sites/:site/domain-move/:source/:target
- [x] Deploy a specific VCS branch or tag to an environment.
  - POST /sites/:site/envs/:env/code-deploy
- [x] Delete a site environment database instance backup.
  - DELETE /sites/:site/envs/:env/dbs/:db/backups/:backup
- [x] Restore a site environment database instance backup.
  - POST /sites/:site/envs/:env/dbs/:db/backups/:backup/restore
- [x] Configure Live Development on an environment.
  - POST /sites/:site/envs/:env/livedev/:action
- [x] List an environment’s domains.
  - GET /sites/:site/envs/:env/domains
- [x] Get a domain record.
  - GET /sites/:site/envs/:env/domains/:domain
- [x] Delete a domain.
  - DELETE /sites/:site/envs/:env/domains/:domain
- [x] Add a domain name.
  - POST /sites/:site/envs/:env/domains/:domain
- [x] Purge the Varnish cache for a domain
  - DELETE /sites/:site/envs/:env/domains/:domain/cache

**Comment by Zlender** [comment]
#73 fixes the problem with installing from a Drupal project. I think the make file should also work fine.
